name = "M4A1TOOLS"
id = "M4A1TOOLS"
maintainer = "MACHIN3, TitusLVR, AIGODLIKE Community"
version = "2.0.1"
tagline = "Based on the M3 tool, add more features to make Blender more user-friendly"
blender_version_min = "4.0.0"
type = "add-on"
schema_version = "2.0.0"
tags = ["3D View"]
license = ["license"]
website = "https://blender.org"
