def origin_text(a, b):
    return "Add an empty object origin as the rotation axis (if there is an " \
           "origin, " + a + \
        "), and set the origin position " + b + " during operation"
desc = "Set Object Origin to Bounding Box Bottom Center"
desc += "\nALT: Determine Bottom Center based on Evaluated Mesh, taking Modifiers into account"
not_add = "do not add it"
data = {
    "Create new Pose based on {}'s current Rotation":"基于 {} 当前的旋转创建新的姿势",
    "Create linked Batch Poses for {} and all Group Empties under it":"为 {} 及其下所有组空物体创建链接的批处理姿势",
    'Select Box': '框选',
    'Hyper Cursor': '高级光标',
    'Simple Hyper Cursor': '简易高级光标',
    # 'Select Box': '框选',
    'Select Lasoo': '套索选择',
    'Entering the sculpt mode will be displayed in the top bar': '进入雕刻模式将会在顶栏显示',
    'theKeyActionIsAClick': '按键操作是单击',
    'writePropertyFileError': '写入属性文件错误',
    'DisplayedAllTheTime': '一直显示',
    'SculptModeOnly': '仅雕刻模式',
    'BbrushModeOnly': '仅Bbrush模式',
    'NotShown': '不显示',
    'Keep the silhouette displayed all the time, even when not in sculpting mode': '一直保持显示剪影图,即使不在雕刻模式',
    'Display silhouette images only in sculpting mode': '仅在雕刻模式显示剪影图',
    'Only in Bbrush mode, the silhouette is displayed': '仅在Bbrush模式时,显示剪影图',
    'Never display silhouette images at any time': '任何时候都不显示剪影图',
    'Silhouette Display Mode': '剪影图显示模式',
    'Silhouette image scaling': '剪影图缩放',
    'Silhouette image offset X': '剪影图偏移X',
    'Silhouette image offset Y': '剪影图偏移Y',
    'Shortcut key offset X': '快捷键偏移X',
    'Shortcut key offset Y': '快捷键偏移Y',
    'Always use Bbrush sculpting mode': '始终使用Bbrush雕刻模式',
    'If entering sculpting mode, Bbrush mode will automatically activate; if exiting sculpting mode, Bbrush mode will deactivate': '如果进入雕刻模式则自动开启Bbrush模式,退出雕刻模式则退出Bbrush模式',
    'Depth ray check size': '深度射线检查大小',
    'Display shortcut keys': '显示快捷键',
    'Shortcut key offset': '快捷键偏移',
    'Shortcut key display size': '快捷键显示大小',
    'Silhouette:': '剪影图',
    'shortcut:': '快捷键',
    'Setting log file path error': '设置Log文件路径错误',
    "Check if the mouse is placed over the model, mouse cursor's range size": '检查鼠标是否放在模型上,鼠标范围大小',
    'Control handle for moving the sculpting origin': '用于移动雕刻原点的操作控制柄',
    'Polygon mask': '多边形绘制遮罩',
    'Draw polygonal mask': '绘制多边形遮罩',
    'Square mask': '方形绘制遮罩',
    'Draw square mask': '绘制方形遮罩',
    'Circular mask': '圆形绘制遮罩',
    'Draw circular mask': '绘制圆形遮罩',
    'Ellipse mask': '椭圆遮罩',
    'Draw elliptical mask': '绘制椭圆遮罩',
    'View operations': '视图操作',
    'Pan view': '平移视图',
    'Rotate view': '旋转视图',
    'Zoom view': '缩放视图',
    'Tilt view': '倾斜视图',
    'alt+right or alt+middle': 'ALT+右键 or ALT+中键',
    'alt+left Drag in blank area': '在空白处ALT+左键拖拽',
    'shift+middle': 'shift+中键',
    'left Drag in blank area': '在空白处左键拖拽',
    'ctrl+middle or ctrl+right': 'ctrl+中键 或 ctrl+右键',
    'shift+left Drag in blank area': '在空白处shift+左键拖拽',
    'left Paint on the model': '左键在模型上绘制',
    'alt+left Paint on the model': 'alt+左键在模型上绘制',
    'shift+left Paint on the model': 'shift+左键在模型上绘制',
    'alt+left Click on other models': 'alt+左键在模型上单击',
    'ctrl+left Paint on the model': 'ctrl+左键在模型上绘制',
    'ctrl+alt+left Paint on the model': 'ctrl+alt+左键在模型上绘制',
    'ctrl+left Drag in blank area': '在空白处ctrl+左键拖拽',
    'ctrl+left Drag from a blank area to the model': '在空白处ctrl+左键拖拽到模型上',
    'ctrl+alt+left Drag from a blank area to the model': '在空白处ctrl+alt+左键拖拽到模型上',
    'ctrl+left Click on the model': 'ctrl+左键单击模型',
    'ctrl+alt+left Click on the model': 'ctrl+alt+左键在模型上单击',
    'ctrl+alt+left Drag in blank area': '在空白处ctrl+alt+左键拖拽',
    'ctrl+Numpad+ Click': 'ctrl+数字+ 左键单击',
    'ctrl+Numpad- Click': 'ctrl+数字- 左键单击',
    'ctrl+Up arrow or ctrl+Numpad* Click': 'ctrl+方向上 或 数字* 左键单击',
    'ctrl+Down arrow or ctrl+Numpad/ Click': 'ctrl+方向下 或 数字/ 左键单击',
    'ctrl+shift+left Paint on the model': 'ctrl+shift+左键在模型上绘制',
    'ctrl+shift+alt+left Paint on the model': 'ctrl+shift+alt+左键在模型上绘制',
    'ctrl+shift+left Click in blank area': '在空白处ctrl+shift+左键单击',
    'ctrl+shift+left or ctrl+shift+alt+left Drag in blank area': '在空白处ctrl+shift 或 ctrl+shift+alt+左键拖拽',

    'mouse_right': '右键',
    'middle': '中键',
    'left': '左键',
    'click': '单击',
    'Numpad': '小键盘',
    'Reverse sculpt': '反向雕刻',
    'Smooth': '平滑',
    'Switch object': '切换雕刻物体',
    'Draw mask': '绘制遮罩',
    'Erase mask': '擦除遮罩',
    'Invert mask': '反转遮罩',
    'Marquee mask': '框选遮罩',
    'erase mask': '框选擦除遮罩',
    'Fade mask': '淡化遮罩',
    'Clear mask': '清除遮罩',
    'Sharpen mask': '锐化遮罩',
    'Fill mask': '填充遮罩',
    'Grow mask': '生长遮罩',
    'Shrink mask': '收缩遮罩',
    'Increase contrast': '提高遮罩对比度',
    'Decrease contrast': '降低遮罩对比度',
    'Hide': '隐藏',
    'Hide outside': '隐藏绘制框外',
    'Hide inside': '隐藏绘制框内',
    'Unhide': '取消隐藏',
    'Invert visibility': '反转隐藏',
    'Up arrow': '上箭头',
    'Down arrow': '下箭头',
    'Brush mode switch': '笔刷模式切换',
    'Switch brush content, with a list of options for each key, including [sculpt, mask, hide]': '切换笔刷内容,每个键的列表，有[雕刻,遮罩,隐藏]三个功能',
    'Depth map zoom value': '深度图缩放值',
    'Bbrush sculpting': 'Bbrush雕刻',
    'Sculpting in the style of Zbrush': '使用Zbrush的方式雕刻',
    'Only the front faces': '仅前面的面',
    'The key operation is a single click': '按键操作是单击',
    'Error in acquiring shape projection': '获取形状投射错误',
    'Bbrush mask': 'Bbrush遮罩',
    'Mask brush': '遮罩笔刷',
    'Display top text': '显示顶部文本',
    'Depth ray check size(px)': '深度射线检查大小(px)',
    'Mirror vertex groups weights, clean vertex groups': '镜像顶点组，清理顶点组',
    'Mirror weights': '镜像顶点组',
    'Mirror vertex groups weights': '镜像顶点组权重',
    'Clear unused': '删除没有使用',
    'Clear zero': '删除权重为零',
    'Mirror completed!': '镜像完毕!',
    'You cannot select both left and right bones simultaneously!': '不能同时选择左右两边的骨骼!',
    'Multiple vertex groups will be mirrored.': '将会镜像多个顶点组',
    'The object does not have vertex groups.': '对象没有顶点组',
    'Delete vertex groups with a total weight of 0 within the vertex group.': '删除权重为0的顶点组',
    'Delete unused vertex groups.': '删除没有使用的顶点组',
    'Mirror method': '镜像方法',
    'Nearest': '最近点',
    'Polyinterp': '面插值',
    'Nearest vertex': '最近的顶点',
    'Nearest face interpolation': '最近的面插值',
    'Mirror direction': '镜像方向',
    'Select mirror direction': '选择镜像方向',
    'Symmetric': '对称',
    'Multiple vertex groups': '多个顶点组',
    'Mirror or symmetrize multiple vertex groups.': '镜像或者对称多个顶点组',
    'Selected': '选中的',
    'Delete vertex groups with a total weight of 0': '删除总权重为0的顶点组',
    'Mirror or symmetrize selected vertex groups (selected bones, in weight paint mode)': '镜像或者对称选中的顶点组(选中的骨骼，需要在权重绘制模式)',
    'When enabled, make the middle bone symmetrical weight; when disabled, mirror the weight between the left and right bones.': '开启时使中间骨骼对称权重，关闭时使左右两边的骨骼镜像权重',
    '(-x arrow<-) Use the weight on the right side +x -> -x': '(-x箭头<-)使用右边权重+x->-x',
    '(+x arrow->) Use the weight on the left side -x -> +x': '(+x箭头->)使用左边权重-x->+x',
    'When left and right are symmetrical, the nearest point effect is better; when they are not symmetrical, use face interpolation.': '左右对称时最近点效果好，左右不对称时使用面插值',
    "Delete unused vertex groups (deformation bones, modifiers), excluding those used by other objects.": '删除没有使用的顶点组（形变骨骼，修改器），不包括被其他物体使用的顶点组',
    'Adjust the wave modifier': '调整波修改器',
    'WaveHelper': '波浪修改器',
    'Motion': '运动',
    'Along Normals': '沿法向',
    'Falloff': '衰减',
    'Vertex Groups': '顶点组',
    'Animation': '动画',
    'Total frame count for looping': '循环总帧数',
    'Total frame count for motion': '运动总帧数',
    'Frame Start': '起始帧',
    'Frame Zero': '归零帧',
    'Frame End': '结束帧',
    'Frame Stop': '停止帧',
    'Full stop frame': '完全停止帧',
    'Damping': '阻尼',
    'Offset': '偏移量',
    'Set loop animation': '设置循环动画',
    'Width': '波宽度',
    'Width of each wave': '每个波的宽度',
    'High precision': '高精度',
    'Wave spacing': '波间隔',
    'The spacing between each wave': '每个波之间的间隔',
    'Frequency': '频率',
    'In one second, the number of oscillations of particles, directly expressed as the reciprocal of the period': '一秒内，粒子的振动次数，直接表示为周期的倒数',
    'Direction': '方向',
    'Diffusion': '扩散',
    'Shrink': '收缩',

    'Default lattice resolution': '默认晶格分辨率',
    'Interpolation': '插值',
    'Mode': '模式',
    'Lattice Helper': '晶格助手',
    'Lattice overlay': '晶格覆盖',
    'Automatically add a lattice to selected objects': '自动为选中物体添加晶格',
    'Set parent': '设置父级',
    'If in Object Mode, set the lattice as the parent of the object.If in lattice Editing Mode, set the active object as the parent of the lattice': '如果在物体模式下,将设置晶格为物体的父级,如果在网格编辑模式下,将设置活动物体为晶格父级',
    'Set the active item as the parent of other selected objects': '设置活动项为其它选中物体父级',
    'entirety': '整体',
    'All selected vertices as a single entity': '所有选择顶点作为一个整体',
    'Bounding box': '边界框',
    'Selection block (edit mode)': '选择块(编辑模式)',
    'Entire block (edit mode)': '整个块(编辑模式)',
    'Add a lattice for each selected block as a separate region within edit mode': '将编辑模式内每一个选择的块作为单独的一个区域添加一个晶格',
    'Add a lattice for all selected blocks within edit mode as a single region': '将编辑模式内所有选择的块作为一个区域添加晶格',
    'Specify a vertex group for the modifier': '为修改器指定顶点组',
    'Generate a vertex group based on the selected mode': '根据所选的模式生成顶点组',
    'All selected objects as a single entity': '所有选择物体作为一个整体',
    'Use the bounding box of each selected object as a separate lattice': '以每一个选择物体的边界框作为一个单独的晶格',
    'Objects without selection to add lattices': '未选择可添加晶格物体',
    'Apply lattice': '应用晶格',
    'Delete lattice': '删除晶格',
    'Automatically apply the lattice modifier': '自动应用晶格修改器',
    'Apply the lattice modifier': '应用晶格修改器',
    'Apply the lattice modifier as a shape key': '应用晶格修改器为形态键',
    'Save the lattice modifier as a shape key': '保存晶格修改器为形态键',
    'Delete the lattice modifier': '删除晶格修改器',
    'Delete the lattice': '删除晶格',
    'When applying or deleting the lattice modifier, remove the specified lattice for the selected lattice or selected objects': '在应用或删除晶格修改器时,删除所选晶格或所选物体所设修改器指定晶格',
    'Delete the used vertex group': '删除使用的顶点组',
    'Delete the vertex group used by the lattice modifier, and simultaneously remove the vertex group used by the lattice modifier when applying or deleting it': '删除晶格修改器使用的顶点组,在应用或删除晶格修改器时同时删除晶格修改器所使用的顶点组',
    'skip applying the modifier': '跳过应用修改器',
    'type not supported for applying lattice modifier': '类型不支持应用晶格修改器',

    "Show Toggle Bend Axis Gizmo": "显示切换弯曲轴向Gizmo",
    "AIGODLIKE Community:小萌新": "AIGODLIKE社区,小萌新",
    "AIGODLIKE": "辣椒出品",
    "Gizmo Property Show Location": "Gizmo属性显示位置",
    "You can press the following shortcut keys when dragging values":
        "拖动值时可以按以下快捷键",
    "    Wheel:   Switch Origin Ctrl Mode":
        "    滚轮:   切换原点控制模式",
    "    X,Y,Z:  Switch Modifier Deform Axis":
        "    X,Y,Z:  切换修改器型变轴",
    "    W:       Switch Deform Wireframe Show":
        "    W:       切换形变线框显示",

    "    A:       Switch To Select Bend Axis Mode(deform_method=='BEND')":
        "    A:       切换到选择弯曲轴模式(形变方法='弯曲')",
    "Show Set Axis Button": "显示设置轴向Gizmo",
    "Follow Upper Limit(Red)": "跟随上限(红色)",
    "Follow Lower Limit(Green)": "跟随下限(绿色)",
    "Lower limit(Green)": "下限(绿色)",
    "UP Limits(Red)": "上限(红色)",
    "Show Deform Wireframe": "显示形变线框",

    "Minimum value between upper and lower limits": "上限与下限之间的最小值",
    "Upper and lower limit tolerance": "上下限容差",

    "Draw Upper and lower limit Bound Box Color": "绘制网格上限下限边界线框的颜色",
    "Upper and lower limit Bound Box Color": "上限下限边界框颜色",
    "Draw Bound Box Color": "绘制网格边界框的颜色",
    "Bound Box": "边界框颜色",
    "Draw Deform Wireframe Color": "绘制网格形变形状线框的颜色",
    "Deform Wireframe": "形变线框颜色",

    "Simple Deform visualization adjustment tool": "简易形变可视化工具",

    "Select an object and the active modifier is Simple Deform":
        "选择物体并且活动修改器为简易形变",
    "Bound Middle": "边界框中心",
    origin_text(not_add, "as the lower limit"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为下限位置",
    origin_text(not_add, "as the upper limit"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为上限位置",
    origin_text("it will not be added",
                "between the upper and lower limits"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为上下限之间的位置",
    origin_text(not_add,
                "as the position between the bounding boxes"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为边界框之间的位置",
    "No origin operation": "不进行原点操作",
    "Origin control mode": "原点控制模式",
    "Down limit": "下限",
    "Coefficient": "系数",
    "Up limit": "上限",
    "Upper limit": "上限",

    "3D View -> Select an object and the active modifier is simple "
    "deformation": "3D视图 -> 选择一个物体,"
                   "并且活动修改器为简易形修改器",

    "3D View: Simple Deform Helper": "3D 视图: Simple Deform Helper 简易形变助手",
    "Tool Options": "工具选项",
    "The scaling value of the object is not 1": "对象的缩放值不是1",

    "which will cause the deformation of the simple deformation "
    "modifier.": "这将导致简易形变修改器变形",
    "Please apply the scaling before deformation.": "请应用缩放",

    'Grid overlay': '网格覆盖',
    'Automatically add grid overlay to selected objects': '自动为选中物体添加网格覆盖',
    'Grid binding': '网格绑定',
    'Add grid modifier to a subset of this grid': '添加网格修改器到该网格的子集',
    'Apply deformation modifier': '应用形变修改器',
    'Automatically apply deformation modifier': '自动应用形变修改器',
    'Apply modifier': '应用修改器',
    'Apply modifier as a shape key': '应用修改器为形态键',
    'Save modifier as a shape key': '保存修改器为形态键',
    'Delete modifier': '删除修改器',
    'Delete the grid used by the deformation modifier': '删除形变修改器所使用网格',
    'When applying or deleting the modifier, remove the specified grid for the selected modifier or selected objects with a deformation modifier': '在应用或删除修改器时删除所选或所选物体所设形变修改器所指定的网格',
    'MeshDeformHelper': '网格形变助手',
    'Create convex hull': '创建凸包',



    "Smart Vert": '智能顶点',
    "Smart Vertex Merging, Connecting and Sliding": '智能顶点合并、连接和滑动',
    "Smart Edge Creation, Manipulation, Projection and Selection Conversion": '智能边缘创建、操作、投影和选择转换',
    "Smart Face": '智能面',
    "Smart Face Creation and Object-from-Face Creation": '智能面创建和从面创建物体',
    "Old Modifier": '老版修改器',
    "Enable Old Modifier": '启用老版修改器',
    "Mirror Vertex Group": '镜像顶点组',
    "Mirror Vg": '镜像顶点组',
    "Wave Modifier": '波浪修改器',
    "Meshdeform Helper": '网格形变助手',
    "Simple Deform Helper": '简易形变助手',
    "Convenient and Quick Grid Creation": '方便快捷创建晶格',
    "User-friendly Visual 3D Components": '好用的可视化的3d组件',
    "Quick Setup Mesh Deformation": '快速设置网格形变',
    "Improve Parameter Display for Wave Modifier": '为波浪修改器添加更好的参数显示',
    "Quick Geometry Clean-up": '快速几何清理',
    "Edge Constraint": '边缘约束',
    "Edge Constrained Rotation and Scaling": '边缘约束旋转和缩放',
    "PunchIt Manifold Extrusion and Cursor Spin": 'PunchIt流形挤出和光标旋转',
    "Focus": '聚焦',
    "Object Focus and Multi-Level Isolation": '物体聚焦和多级隔离',
    "Flick Object Mirroring and Un-Mirroring": '对象镜像与取消镜像',
    "Object per-axis Location, Rotation and Scale Alignment, as well as Object-Inbetween-Alignment": '物体按轴位置、旋转和比例对齐，以及物体之间的对齐',
    "Group Objects using Empties as Parents": '将对象分组，使用空物体作为父对象',
    "Smart Drive": '智能驱动',
    "Use one Object to drive another": '使用一个物体来驱动另一个物体',
    "Clipping Toggle": '裁剪切换',
    "Viewport Clipping Plane Toggle": '视口裁剪平面切换',
    "Mesh Cut": '网格切割',
    "Knife Intersect a Mesh-Object, using another one": '用另一个网格对象刀具相交一个网格对象',
    "Customize": '自定义',
    "Customize various Blender preferences, settings and keymaps": '自定义各种Blender首选项、设置和按键映射',
    "Modes Pie": '模式菜单',
    "Quick mode changing": '快速模式切换',
    "Save Pie": '保存菜单',
    "Save, Open, Append and Link. Load Recent, Previous and Next. Purge and Clean Out. ScreenCast and Versioned Startup file": '保存、打开、追加和链接。加载最近、上一个和下一个。清除和清理。录屏和版本化启动文件。',
    "Alignments Pie": '对齐菜单(面/uv)',
    "Edit mesh and UV alignments": '编辑网格和UV对齐',
    "Align Helper Pie": 'popoti对齐助手',
    "Align Pie": '对齐菜单(编辑模式/UV)',
    "Align Helper": 'popoti对齐助手',
    "Object Alignment Assistant": '物体对齐助手',
    "Cursor and Origin Pie": '光标原点菜单',
    "Cursor and Origin": '光标原点菜单',
    "Cursor and Origin manipulation": '光标和原点操作',
    "Collections Pie": '集合菜单',
    "Collection management": '集合管理',
    "Tools Pie": '工具菜单',
    "Switch Tools, useful with BoxCutter/HardOps and HyperCursor": '切换工具，与BoxCutter/HardOps和HyperCursor一起使用很有用',
    "Print Addon Registration Output in System Console": '在系统控制台中打印插件注册输出',
    "The M4A1 tool is a comprehensive Blender enhancement tool developed based on machine3Tools (GPL)": 'M4A1工具是一款基于machine3Tools（GPL）开发的综合搅拌机增强工具',
    "Show Sidebar Panel": '显示侧边栏面板',
    "HUD Scale": 'HUD 比例',
    "Mirror Flick Distance": '镜像抖动距离',
    "Fade time": '淡入淡出时间',
    "Clean Up": '清理',
    "Select Hierarchy": '选择层次',
    "Viewport Tweening": '视口补间',
    "Ignore Lights (keep them always visible)": '忽略灯光（使它们始终可见）',
    "Sub Menu": '子菜单',
    "Use Group Sub Menu in Object Context Menu": '在对象上下文菜单中使用组子菜单',
    "Outliner Toggles": '大纲切换',
    "Remove Empty": '移除空物体',
    "Show Group Toggles in Outliner Header": '在大纲标题中显示组切换',
    "Automatically remove Empty Groups in each Cleanup Pass": '在每次清理过程中自动移除空组',
    "Auto Name": '自动命名',
    "Prefix": '前缀',
    "Suffix": '后缀',
    "Default Empty Draw Size": '默认空物体绘制大小',
    "Fade Sub Group Sizes": '淡化子组大小',
    "Factor": '系数',
    "Input & Navigation": '输入与导航',
    "Keymaps": '按键映射',
    "Startup": '启动',
    "Keymaps have been modified, restore them first.": '按键映射已被修改，请先恢复它们。',
    "Restore now": '立即恢复',
    "Toggle Cavity/Curvature OFF in Edit Mode, ON in Object Mode": '在编辑模式下关闭凹凸/曲率开关，在对象模式下打开',
    "Toggle X-Ray ON in Edit Mode, OFF in Object Mode, if Pass Through or Wireframe was enabled in Edit Mode": '在编辑模式下，如果启用了穿透或线框模式，则将 X 射线打开，在对象模式下关闭。',
    "Sync Tool if possible, when switching Modes": '在可能的情况下，切换模式时同步工具',
    "Import / Export": '导入/导出',
    "Show .obj Import/Export": '显示 .obj 导入/导出',
    "Show Plasticity Import/Export": '显示塑性导入/导出',
    ".obj import/export with Axes set up already": '已设置轴的 .obj 导入/导出',
    "Show .fbx Import/Export": '显示 .fbx 导入/导出',
    "Use 'Fbx All' for Applying Scale": '使用“Fbx All”来应用比例',
    "Show .usd Import/Export": '显示 .usd 导入/导出',
    "Show .stl Import/Export": '显示 .stl 导入/导出',
    "Screen Cast": '屏幕录制',
    "Show Screencast in Save Pie": '在保存pie中显示屏幕录制',
    "Operator Count": '操作符数量',
    "Font Size": '字体大小',
    "Highlight Operators from M4A1 addons": '突出显示来自 M4A1 插件的操作符',
    "Display Operator's Addon": '显示操作符的插件',
    "Display Operator's bl_idname": '显示操作符的 bl_idname',
    "Use SKRIBE (dedicated, preferred)": '使用 SKRIBE（专用，首选）',
    "Use Screencast Keys (addon)": '使用 Screencast Keys（插件）',
    "Pre-Undo Save": '预撤销保存',
    "Make Pre-Undo Saving available in the Pie": '在饼图中提供预撤销保存',
    "Useful if you notice Undo causing crashes": '如果你注意到撤销导致崩溃，这将非常有用',
    "Versioned Startup File": '版本化的启动文件',
    "Use CTRL + U keymap override": '使用CTRL + U键映射覆盖',
    "npanel text": 'n面板文字',
    "Show Cursor and Selected to Grid": '显示光标和选定内容到网格',
    "Set Transform Preset when Setting Cursor": '设置光标时设置变换预设',
    "Show BoxCutter Presets": '显示 BoxCutter 预设',
    "Show Hard Ops Menu": '显示 Hard Ops 菜单',
    "Show Quick Favorites": '显示快速收藏',
    "Show Tool Bar": '显示工具栏',
    "No tools or pie menus with settings have been activated.": '未激活任何工具或带有设置的饼菜单。',
    "No keymappings available, because none of the tools have been activated.": '没有可用的按键映射，因为没有激活任何工具。',
    "No keymappings created, because none of the pies have been activated.": '因为没有激活任何饼菜单，所以没有创建按键映射。',
    "Merge Last": '合并最后',
    "Merge Center": '合并中心',
    "Merge Paths": '合并路径',
    "Connect Paths": '连接路径',
    "Slide Extend": '滑动延伸',
    "Smart Edge": '智能边缘',
    "Toggle Sharp/Weight": '切换锐边/权重',
    "Offset Edges": '偏移边缘',
    "View Selected": '查看所选',
    "Local View": '局部视图',
    "Local": '局部',
    "World": '世界',
    "Local View (Inverted)": '局部视图（反转）',
    "Flick Mirror": '快速镜像',
    "Object Mode": '对象模式',
    "Pose Mode": '姿势模式',
    "Open Filebrowser": '打开文件浏览器',
    "Open .blend File": '打开 .blend 文件',
    "Toggle Sorting": '切换排序',
    "Toggle Display": '切换显示',
    "Cycle Thumbs Forwards": '向前循环缩略图',
    "Cycle Thumbs Backwards": '向后循环缩略图',
    "Toggle Hidden": '切换隐藏',
    "Create Group": '创建组',
    "Select Group": '选择组',
    "Toggle Group Mode": '切换组模式',
    "Expand Outliner": '展开大纲',
    "Collapse Outliner": '折叠大纲',
    "Toggle Children": '切换子项',
    "Save, Open, Append": '保存,打开,附加',
    "Save Versioned Startup File": '保存版本化的启动文件',
    "Current file is unsaved. Start a new file anyway?": '当前文件未保存。仍然要开始新文件吗？',
    "Save the current file in the desired location\nALT: Save as Copy\nCTRL: Save as Asset": '将当前文件保存在所需位置\nALT：另存为副本\nCTRL：另存为资源',
    "Incremental Save": '增量保存',
    "Save unsaved file as...": '将未保存的文件另存为...',
    "Load most recently used .blend file": '加载最近使用的 .blend 文件',
    "Load Most Recent": '加载最近的',
    "M4A1: Load previous file": 'M4A1：加载上一个文件',
    "M4A1: Load next file": 'M4A1：加载下一个文件',
    "Open System's Temp Folder, which is used to Save Files on Quit, Auto Saves and Undo Saves": '打开系统的临时文件夹，该文件夹用于在退出时保存文件，自动保存和撤销保存',
    "M4A1: Purge Orphans": 'M4A1：清理孤立物',
    "Clean out .blend file!": '清理 .blend 文件！',
    "M4A1: Reload Linked Liraries": 'M4A1：重新加载链接的库',
    "M4A1: Screen Cast": 'M4A1：屏幕录制',
    "Screen Cast Operators": '屏幕录制操作',
    "Screen Cast recent Operators and Keys": '屏幕录制最近的操作和按键',
    "Screen Cast Recent Operators": '最近的屏幕录制操作',
    "INFO: Enabling Screencast Keys Addon": '信息：启用屏幕录制按键插件',
    "turning skribe ON!": '打开 SKRIBE！',
    "Open Temp Dir": '打开临时目录',
    "(R) Most Recent": "(R) 最近的",
    "Import": '导入',
    "All Recent": '所有最近的',
    "Save As..": '另存为..',
    "Cursor Pie": '游标菜单',
    "Doubles": '重叠',
    "Redundant": '冗余',
    "Chamfer": '倒角',
    "Korean Bevel": '韩式斜边',
    "Bounds/Region": '范围/区域',

    "Recalculate Normals": '重新计算法线',
    "Non-Manifold": '非流形',
    "Non-Planar": '非平面',
    "Tris": '三角',
    "Ignore Mirrors": '忽略镜像',
    "Drive it!": '添加驱动',
    "Group.": '打组',
    "Un-Group": '取消组',
    "Groupify": "分组化",
    "Duplicate Group": '复制组',
    "Add to Group": '添加到组',
    "Remove from Group": '从组删除',
    "Hide Empties": '隐藏空物体',
    "Recursive": '递归',
    "Auto Select": '自动选择',
    "Update": '更新',
    "Set Batch Pose": '设置批量姿势',
    "Set Pose": '设置姿势',
    "Alpha.": '透明度',
    "Poses": '姿势',
    "Group Gizmos": '组工具形状',
    "Adjust Group Origin": '调整组原点',
    "Disable, when done!": '完成后禁用',
    "Active Group": '活动组',
    "Global Group Gizmos": '显示全局gizmos',
    "3D View: POPOTI Align Helper": "3D 视图: POPOTI对齐助手",
    "POPOTI Align Helper": "POPOTI对齐助手",
    "World Original": "世界原点",
    "More friendly alignment based on observation perspective": "更友好的基于观察视角的对齐",
    "Tool Panel": "工具面板",
    "Axis to be aligned": "需要对齐的轴",
    "Select the axis to be aligned, multiple choices are allowed": "选择需要进行对齐的轴,可多选",
    "Align X Axis": "对齐X轴",
    "Align Y Axis": "对齐Y轴",
    "Align Z Axis": "对齐Z轴",
    "Min Point": "最小点",
    "Max Point": "最大点",
    "Center Align": "中心对齐",
    "Align to Min Point": "对齐到最小点",
    "Align to Max Point": "对齐到最大点",
    "Distribution": "分布",
    "Distribution Align": "分布对齐",
    "General alignment, you can set the alignment of each axis(maximum, center, minimum)": "常规对齐,可以设置每个轴的对齐方式(最大,居中,最小)",
    "Align to Cursor(Scale reset 1)": "对齐到游标(缩放将重置为1)",
    "Align to Active Object": "对齐到活动物体",
    "Aligning to the world origin is the same as resetting": "对齐到世界原点,和重置功能相同",
    "Sort distribution by X axis": "按X轴排序分布",
    "Sort distribution by Y axis": "按Y轴排序分布",
    "Sort distribution by Z axis": "按Z轴排序分布",
    "Align and sort the selected objects according to the selection axis to obtain the correct movement position": "按选择轴对所选物体进行对齐并排序,以获取正确的移动位置",
    "Distribution sort axis": "分布排序轴",
    "Lowest Object": "最低物体",
    "All Object": "所有物体",
    "Sort Axis": "排序轴",
    "Ground": "地面",
    "Align Ground": "对齐地面",
    "Adjustment": "调整",
    "Distribution interval value": "分布间隔距离",
    "Active": "活动项",
    "Not Selected Active Object": "未选择活动物体",
    "Fixed the nearest and farthest objects": "固定最远和最近的物体,按间距自动排列中间的物体",
    "Adjust the distance between each object(Fixed active object)": "调整每个对象之间的距离(固定活动对象位置)",
    "Show Button Text": "显示按钮文字",
    "Align To Ground Object": "对齐到地面物体",
    "To Object": "到物体",
    "History Unmirror": '历史取消镜像',
    "History Object": '历史对象',
    "Group Pose Matrix": '组姿势矩阵',
    "Remove Pose": '移除姿势',
    "Batch Pose": '批量姿势',
    "Toggle Connection to Other Batch Poses in this Group Hierarchy\n\nIf the active pose is disconnected, it will be retrieved like a regular single Pose.\nDisconnected Batch Poses in the Group Hierarchy below, will not be previewed, retrieved or removed, unless overriden in the Retrieve/Remove ops": '切换与此组层次结构中的其他批处理姿势的连接如果活动姿势未连接，它将像常规单个姿势一样被检索。在下面的组层次结构中，未连接的批处理姿势将不会被预览、检索或移除，除非在检索/移除操作中进行覆盖。',
    "Use Undo Save": '使用撤销保存',
    "Use Redo Save": '使用重做保存',
    "Save before Undoing\nBe warned, depending on your scene complexity, this can noticably affect your undo speed": '撤销前保存\n请注意，根据您的场景复杂性，这可能会显着影响您的撤销速度',
    "Also save before first Operator Redos": '在第一次操作重做之前也要保存',
    "Pass Through": '穿透',
    "Show Edit Mesh Wireframe": '显示编辑网格线框',
    "Sync Selection": '同步选择',
    "Eevee Preset": 'Eevee预设',
    "Eevee Quality Presets": 'Eevee质量预设',
    "Set Use Scene Lights": '设置使用场景灯光',
    "Set Use Scene Lights when changing Eevee Preset": '更改 Eevee 预设时，设置使用场景灯光',
    "Set Use Scene World": '设置使用场景环境',
    "Set Use Scene World when changing Eevee Preset": '更改 Eevee 预设时，设置使用场景环境',
    "Show Smart Drive": '显示智能驱动',
    "Driver Start Value": '驱动器起始值',
    "Driver End Value": '驱动器结束值',
    "Driver Axis": '驱动轴',
    "Driver Transform": '驱动器变换',
    "Driver Space": '驱动空间',
    "Driven Start Value": '被驱动起始值',
    "Driven End Value": '被驱动结束值',
    "Driven Axis": '被驱动轴',
    "Driven Transform": '被驱动变换',
    "Driven Lmit": '被驱动限制',
    "BoxCutter Orientation": '剖切工具方向',
    "Show Group": '显示组',
    "Show Group Gizmos": '显示组gizmos',
    "Show Group Gizmo": '显示组gizmos',
    "Toggle Group Gizmos Globally": '全局切换组控件',
    "Auto Select Groups": '自动选择组',
    "Automatically select the entire Group, when its Empty is made active": '当其空物体激活时自动选择整个组',
    "Recursively Select Groups": '递归选择组',
    "Recursively select entire Group Hierarchies down": '递归向下选择整个组层次结构',
    "Hide Group Empties in 3D View": '在3D视图中隐藏组空对象',
    "Hide Group Empties in 3D View to avoid Clutter": "在3D视图中隐藏组空物体以避免杂乱",
    "Show Auto Select Toggle in main Object Context Menu": "在主对象上下文菜单中显示自动选择切换",
    "Show Recursive Selection Toggle in main Object Context Menu": "在主对象上下文菜单中显示递归选择切换",
    "Show Group Hide Toggle in main Object Context Menu": "在主对象上下文菜单中显示组隐藏切换",
    "Transform only the Group Origin(Empty)": '仅变换组原点（空物体）',
    'Transform the Group Origin(Empty) only, disable Group Auto-Select and enable "affect Parents only"': '仅变换组原点（空物体），禁用组自动选择，并启用"仅影响父级"',
    "Global Group Gizmo Size": '全局组控件大小',
    "Show Assetbrowser Tools": '显示资源浏览器工具',
    "show X rotation gizmo": "显示X轴旋转控件",
    "show Y rotation gizmo": "显示Y轴旋转控件",
    "show Z rotation gizmo": "显示Z轴旋转控件",
    "group gizmo size": '组控件大小',
    "Group Rest Post Matrix": '群组静止状态后的矩阵',
    "Double Click to Rename": '双击重命名',
    "Pose Preview Alpha": '姿势预览透明度',
    "Alpha used to preview Poses across the entire Group": '用于预览整个组中姿势的 Alpha 值',
    "Draw a Preview of the Active Pose": '绘制活动姿势的预览',
    "Smooth Angle": '平滑角度',
    "Has been smoothed": '已经平滑处理',
    "Draw Axes": '绘制坐标轴',
    "Active Object Bevel Toggle": '活动对象倒角切换',
    "Toggle Bevel Shader on Active Object": '切换活动对象上的倒角着色器',
    "Factor to modulate the Bevel Shader Radius on the Active Object": '用于调节活动对象上倒角着色器半径的因子',
    "Active Object Bevel Radius Modulation": '活动对象倒角半径调制',
    "Hash to find associated objects": '用于查找关联对象的哈希值',
    "Group Objects by Parenting them to an Empty": "通过将它们作为空物体的子物体进行分组",
    "Un-Group selected top-level Groups\nALT: Un-Group all selected Groups": '取消对所选顶级组的分组\nALT:取消对所有所选组的分组',
    "Un-Group selected top-level Groups\nALT: Un-Group all selected Groups\nCTRL: Un-Group entire Hierarchy down": '取消对所选顶级组的分组\nALT：取消对所有所选组的分组\nCTRL：取消对整个层次结构向下的分组',
    "Un-Group selected top-level Groups ALT: Un-Group all selected Groups CTRL: Un-Group entire Hierarchy down": '取消对所选顶级组的分组\nALT：取消对所有所选组的分组\nCTRL：取消对整个层次结构向下的分组',
    "Un-Group selected top-level Groups": '取消对所选顶级组的分组',
    "All Selected": '全部选中',
    "Entire Hierarchy": '整个层次结构',
    "Turn any Empty Hirearchy into Group": "将任何空物体层次结构转换为组",
    "Select Group\nCTRL: Select entire Group Hierarchy down": '选择组\nCTRL：选择整个组层次结构向下',
    "Select entire Group Hierarchies down": "选择整个组层次结构向下",
    "Select Top Level Groups\nCTRL: Select entire Group Hierarchy down": "选择顶级组\nCTRL：选择整个组层次结构向下",
    "Duplicate entire Group Hierarchies down\nALT: Create Instances": "复制整个组层次结构向下\nALT：创建实例",
    "Duplicate Top Level Groups\nALT: Create Instances\nCTRL: Duplicate entire Group Hierarchies down": "复制顶级组\nALT：创建实例\nCTRL：复制整个组层次结构向下",
    "Add Selection to Group": '将选定内容添加到组中',
    "Re-Align Group Empty": '重新对齐组空物体',
    "Add Mirror Modifiers, if there are common ones among the existing Group's objects, that are missing from the new Objects": "如果现有组对象中存在的常见镜像修饰符在新对象中缺失，则添加镜像修饰符",
    "Add Object Color, from Group's Empty": "从组的空物体添加对象颜色",
    "Remove Selection from Group": '从组中移除选中',
    "Transform Group": '变换组',
    "Recall Pose + Finish": '撤销姿势 + 完成',
    "Select Group Empty": '选择组的空物体',
    "Setup Group Gizmos": '设置组控件',
    "Setup Group Gizmos ": '设置组控件',
    "5° Angle Snap": '5° 角度捕捉',
    "Set Pose + Finish": '设置姿势 + 完成',
    "Mark Pose for Removal": '标记姿势以移除',
    "Mark All Poses for Removal": '标记所有姿势以移除',
    "Rotate Group": '旋转组',
    " around ": '围绕',
    "Angle: ": '角度：',
    "Snapping": '捕捉',
    "Set Global Size to 1, and compensate each Group's Size accordingly.": "将全局大小设置为1，并相应地补偿每个组的大小。",
    "Toggle All": '切换全部',
    " Disabled": '已禁用',
    "Axes: ": '坐标轴：',
    "Size: ": '大小：',
    "Lock Rotational Axes ": '锁定旋转轴',
    "(those without Gizmos)": '那些没有控件的',
    "Set Group Pose": '设置组姿势',
    "Update active Pose from current Group Empty Rotation": '从当前组空物体的旋转更新活动姿势',
    "Retrieve Selected Group Pose": '检索所选组姿势',
    "Batch Retrieval": '批量检索',
    "Retrieve Up": '向上检索',
    "Retrieve Poses Up the Hierarchy too": '也向上检索层次结构中的姿势',
    "Retrieve Unlinked": '检索未链接的',
    "Retrieve Poses, that have been unlinked too": '检索已取消链接的姿势',
    "Remove related Batch Poses": '移除相关的批处理姿势',
    "Remove Up": '向上移除',
    "Remove Disconnected": '移除断开连接的',
    "Remove all related Batch Poses in the Group Hierarchy": '移除组层次结构中的所有相关批处理姿势',
    "Remove Batch Poses further Up the Hierarchy too": '也移除层次结构中更高级别的批处理姿势',
    "Remove Batch Poses, that have been unlinked too": '移除已取消链接的批处理姿势',
    "Batch Poses to be Removed:": '待移除的批处理姿势：',
    "Drive one Object using another": '使用另一个对象驱动一个对象',
    "M4A1: Bake Group Gizmo Size":"M4A1: 烘焙组控件大小",
    "M4A1: Retrieve Group Pose": "M4A1: 检索组姿势",
    "M4A1: Sort Group Pose":"M4A1: 排序组姿势",
    "Move Selected Group Pose {}": '移动所选组姿势{}',
    "M4A1: Remove Group Pose": "M4A1: 移除组姿势",
    "Local Space Align\nALT: World Space Align\nCTRL: Cursor Space Align": "本地空间对齐\nALT: 世界空间对齐\nCTRL: 光标空间对齐",
    "Straighten verts or edges": '打直顶点或边',
    "Straighten": '打直',
    "Local Space Center\nALT: World Space Center\nCTRL: Cursor Space Center":"本地空间中心\nALT: 世界空间中心\nCTRL: 光标空间中心",
    "Align verts based on min/max UV values": "基于最小/最大UV值对顶点进行对齐",
    "Set Tool by Name": "按名称设置工具",
    "Remove empty Collections": "移除空集合",
    "Select Collection Objects\nSHIFT: Select all Collection Objects\nALT: Deselect Collection Objects\nSHIFT+ALT: Deselect all Collection Objects\nCTRL: Toggle Viewport Selection of Collection Objects": "选择集合对象\nSHIFT：选择所有集合对象\nALT：取消选择集合对象\nSHIFT+ALT：取消选择所有集合对象\nCTRL：切换视口选择集合对象",
    "Create Collection": "创建集合",
    "Create": '创建',
    "Remove Selection from a Collection":"从集合中移除所选内容",
    "Remove from": '移除',
    "Add to": '添加',
    "Move to": '移动',
    "Scene Collections (Selection)": "场景集合（选择）",
    "Scene Collections": '场景集合',
    "Set Selected Objects' Origin to Active Object\nALT: only set Origin Location\nCTRL: only set Origin Rotation": "将所选对象的原点设置为活动对象\nALT：仅设置原点位置\nCTRL：仅设置原点旋转",
    "Set Mesh Object's Origin to Active Vert/Edge/Face\nALT: only set Origin Location\nCTRL: only set Origin Rotation": "将网格对象的原点设置为活动顶点/边缘/面\nALT：仅设置原点位置\nCTRL：仅设置原点旋转",
    "Transform Selected Objects to Cursor\nALT: Only set Location\nCTRL: Only set Rotation": "将所选对象转换到光标位置\nALT：仅设置位置\nCTRL：仅设置旋转",
    "Reset Cursor to World Origin\nALT: Only reset Cursor Location\nCTRL: Only reset Cursor Rotation": "将光标重置到世界原点\nALT：仅重置光标位置\nCTRL：仅重置光标旋转",
    "Invalid Modifier Keys": '无效按键',
    "Align Cursor with Selected Object(s)\nALT: Only set Cursor Location\nCTRL: Only set Cursor Rotation": "将光标与所选对象对齐\nALT：仅设置光标位置\nCTRL：仅设置光标旋转",
    "Align Cursor with Vert/Edge/Face\nALT: Only set Cursor Location\nCTRL: Only set Cursor Rotation": "将光标与顶点/边缘/面对齐\nALT：仅设置光标位置\nCTRL：仅设置光标旋转",
    f"{desc}": '将对象原点设置为边界框底部中心\nALT：基于评估后的网格确定底部中心，考虑到修饰器',
    "Set Selected Objects' Origin to Cursor\nALT: only set Origin Location\nCTRL: only set Origin Rotation": "将所选对象的原点设置为光标位置\nALT：仅设置原点位置\nCTRL：仅设置原点旋转",
    "Set Mesh Object's Origin to Cursor\nALT: only set Origin Location\nCTRL: only set Origin Rotation": "将网格对象的原点设置为光标位置\nALT：仅设置原点位置\nCTRL：仅设置原点旋转",
    "to Origin": '到原点',
    "to Cursor, Offset": '到游标,偏移',
    "to Grid": '到网格',
    "to Selected": '到选择',
    "to Cursor": '到游标',
    "to Geometry": '到几何体',
    "to Active": '到激活',
    "to Bottom": '到底部',
    "Start new .blend file": "开始新的 .blend 文件",
    "Surface Draw, create parented, empty GreasePencil object and enter DRAW mode.\nSHIFT: Select the Line tool.": "表面绘制，创建已设置父级的空涂鸦笔对象，并进入绘制模式。\nSHIFT：选择线条工具。",
    "M4A1: Surface Draw Mode": 'M4A1：表面绘制模式',
    "Versioned Startup File saved: {}": "已保存版本化的启动文件: {}",
    "Initial Startup File saved": "初始启动文件已保存",
    "Direct": '直接',
    "Proximity": '接近',
    "Intersection": '交叉',
    "Plane Intersection": "平面交叉",
    "Projected Plane Intersection": "投影平面交叉",
    "Direct Plane Intersection": '直接平面交叉',
    "MouseDir Plane Intersection": '鼠标方向平面交叉',
    "Mousedir Plane Intersection": '鼠标方向平面交叉',
    "Un-Mirror": "取消镜像",
    "Multiple": '多重',
    "Mirror across Cursor": "以光标为中心镜像",
    "Use Mislinged Object Removal": "使用未对齐对象移除",
    "Use existing Cursor Empty": "使用现有的光标空对象",
    "ROTATE {}": '旋转{}',
    "ROTATE {:.1f}": '旋转 {:.1f}',
    "Adjacent": '相邻',
    "Direction Locked": '方向锁定',
    "SCALE {:.2f}": '缩放 {:.2f}',
    "ZERO SCALE": '零缩放',
    "LOCAL {}": '局部 {}',
    "Individual Origins": '各自的原点',
    "Illegal Sellection": '非法选择',
    "Select one object first, then select the object to be cut last!": '先选择一个对象，然后再选择要切割的对象！',
    "Removes the last modifer in the stack of the selected objects": "移除所选对象堆栈中的最后一个修饰符",
    "Cut a Mesh Object, using another Object.\nALT: Flatten Target Object's Modifier Stack\nSHIFT: Mark Seams": "使用另一个对象剪切网格对象。\nALT：展平目标对象的修改器堆栈\nSHIFT：标记缝隙",
    "Invalid Property Combination": '无效的属性组合',
    "You can't combine {} with {}!": '你不能将 {} 和 {} 结合使用！',
    "Percentage of Segments fading into inner Diameter": '内径渐变段的百分比',
    "Depth in Percentage of minor Diameter": '小直径的百分比深度',
    "Crest": '尖端',
    "Bottom Flank": '底部侧面',
    "Top Flank": '顶部侧面',
    "Add Thread": '添加螺纹',
    "Toggle Object Outlines": '切换对象轮廓线',
    "Stats": '统计信息',
    "(Q) Outline": '(Q) 轮廓',
    "(V) Curvature": '(V) 曲率',
    "Overlays": '覆盖层',
    "(L) Solid": '(L) 实体',
    "Material": '材质',
    "Rendered": '渲染',
    "Auto Smooth Angle": '自动平滑角度',
    "Auto Smooth Angle: None": '自动平滑角度：无',
    "(N) Clear Custom Normals": '(N) 清除自定义法线',
    "Colorize Materials": '着色材质',
    "Autosmooth": '自动平滑',
    "Auto Smooth": '自动平滑',
    "Auto Smooth Angle Presets shown in the Shading Pie as buttons": "在着色饼中显示为按钮的自动平滑角度预设",
    "Shading Pie": '着色菜单',
    "Remove existing 'Auto Smooth' modifier": "移除现有的 '自动平滑' 修饰器",
    "Add 'Auto Smooth' modifier to smooth shade object angle based": "将 '自动平滑' 修饰器添加到基于角度的平滑阴影对象中",
    "Toggle mesh's Auto Smooth property": "切换网格的自动平滑属性",
    "Auto Smooth Angle Preset: {}": '自动平滑角度预设: {}',
    "\nALT: Mark MESH object edges sharp if face angle > auto smooth angle": '\nALT：如果面角度大于自动平滑角度，则标记 MESH 对象边缘为尖锐',
    "\nALT: Clear MESH object sharps, bweights, creases and seams": '\nALT：清除 MESH 对象的尖锐边缘、权重、折痕和缝隙',
    "\n\nSHIFT: Include Children": '\n\nSHIFT：包括子对象',
    "\nCTRL: Include Boolean Objects": '\nCTRL：包括布尔对象',
    "Avoid HyperCursor's Edge Bevels": '避免 HyperCursor 的边缘倒角',
    "Disabled Auto Smooth": '禁用自动平滑',
    "Enabled Auto Smooth": '启用自动平滑',
    "Enabled Auto Smooth with angle {}": '使用角度 {} 启用了自动平滑',
    "(incl. on Instances)": '（包括实例）',
    "Toggle Auto Smooth": '切换自动平滑',
    "Cleared {} Edges": '清除了 {} 边',
    "Marked Edges Sharp {}based on Angle {}": '基于角度 {} 标记了 {} 边缘为尖锐',
    "additively ": '叠加地',
    "Disabled Auto Smooth on {} Objects": '禁用了 {} 对象上的自动平滑',
    "Enabled Auto Smooth on {} Objects carrying Boolean Mods": '已启用了带有布尔修饰器的 {} 个对象的自动平滑',
    " + {} Boolean Mod Objects": '+{}个布尔修饰器对象',
    "+ {} recursive Children": '+{} 个递归子对象',
    "{} Shaded {} selected Objects": '{} 个已选择的对象 {} 着色',
    "Avoid Clearing SubD Creases": '避免清除次级细分折痕',
    "Clear Sharps, BWeights, Creases or Seams": '清除尖锐边、权重、折痕或缝隙',
    "Show Overlays in Solid Shading by default": '默认情况下在实体着色中显示叠加效果',
    "Show Overlays in Material Shading by default": '默认情况下在材质着色中显示叠加效果',
    "Show Overlays in Rendered Shading by default": '默认情况下在渲染着色中显示叠加效果',
    "For a newly created scene, or a .blend file where where it wasn't set before, show Overlays for Solid shaded 3D views": '对于新创建的场景，或者之前没有设置的 .blend 文件，在实体着色的 3D 视图中显示叠加效果',
    "For a newly created scene, or a .blend file where where it wasn't set before, show Overlays for Material shaded 3D views": '对于新创建的场景，或者之前未设置的 .blend 文件，在材质着色的 3D 视图中显示叠加效果',
    "For a newly created scene, or a .blend file where where it wasn't set before, show Overlays for Rendered shaded 3D views": '对于新创建的场景，或者之前未设置的 .blend 文件，在渲染着色的 3D 视图中显示叠加效果',
    "For a newly created scene, or a .blend file where where it wasn't set before, show Overlays for Wire shaded 3D views": '对于新创建的场景，或者之前未设置的 .blend 文件，在线框着色的 3D 视图中显示叠加效果',
    "Show Overlays in Wire Shading by default": '默认情况下在线框着色中显示叠加效果',
    "Toggle Curvature": '切换曲率',
    "Toggle Curvature (Edge Highlighting)": '切换曲率（边缘高亮）',
    "Matcap Switch": 'Matcap 切换',
    "Quickly Switch between two Matcaps": '快速切换两种 Matcap',
    "Toggle Grid": '切换网格',
    "Toggle Grid, distinguish between the grid in regular views and orthographic side views": '切换网格，在普通视图和正交侧视图之间区分',
    "Toggle Cavity": '切换Cavity',
    "Toggle Cavity (Screen Space Ambient Occlusion)": '切换凹陷（屏幕空间环境光遮蔽）',
    "Toggle Outline": '切换轮廓线',
    "WARNING: Object {} could no longer be found": '警告：找不到对象 {} ',
    "{} Overlays for {} Shading": '{} 叠加效果，适用于 {} 着色',
    "Switch to {} shading, and restore previously set Overlay Visibility": '切换到 {} 着色，并恢复先前设置的叠加效果可见性',
    "M4A1: Switch Shading": 'M4A1：切换着色',
    "M4A1: Rotate Studiolight": 'M4A1: 旋转灯光',
    "Rotate Studio Light by {} degrees\nALT: Rotate visible lights too": '旋转 {} 度的工作室灯光\nALT: 也旋转可见灯光',
    "M4A1: Add World": '添加世界环境',
    "M4A1: Adjust Bevel Radius": '调整倒角半径',
    "\n{} {} Bevel Radius": '\n{} {} 倒角半径',
    "\nSHIFT: {} {} Bevel Radius": '\nSHIFT: {} {} 倒角半径',
    "Toggle Wireframe": '切换线框',
    "Toggle Wireframe display for the selected objects\nNothing Selected: Toggle Wireframe Overlay, affecting all objects": '切换所选对象的线框显示\n未选择对象：切换线框叠加显示，影响所有对象',
    "Toggle X-Ray, resembling how edit mode wireframes worked in Blender 2.79": '切换X射线，类似于Blender 2.79中编辑模式下线框显示的方式',
    "M4A1: Colorize Materials": 'M4A1：着色材质',
    "Set Material Viewport Colors from last Node in Material": '从材质中的最后一个节点设置视口颜色',
    "M4A1: Colorize Objects from Materials": 'M4A1：从材质着色对象',
    "Set Object Viewport Colors of selected Objects from their active Materials": '将所选对象的对象视口颜色从其活动材质中设置',
    "M4A1: Colorize Objects from Active": 'M4A1：从活动对象着色对象',
    "Set Object Viewport Colors from Active Object": '从活动对象设置对象视口颜色',
    "M4A1: Colorize Objects from Collections": 'M4A1：从收藏着色对象',
    "Set Object Viewport Colors of selected Objects based on Collections": '基于收藏设置所选对象的对象视口颜色',
    "Multi-Collection Objects": '多收藏对象',
    "Decal Collections": '贴花收藏',
    "Assigned {} unique colors.": '分配了 {} 种独特的颜色。',
    "M4A1: Colorize Objects from Groups": 'M4A1：从组着色对象',
    "Recursively Set Random Object Viewport Colors for Group Objects based on Group Membership\nALT: Set Group Member Colors based on existing Group Empy Colors\nCTRL: Only Colorize the Active Group": '递归地根据组成员身份为组对象设置随机的对象视口颜色\nALT：根据现有的组空颜色设置组成员的颜色\nCTRL：仅着色活动组',
    "Recursively Set Random Object Viewport Colors for Group Objects based on Group Membership\nALT: Set Group Member Colors based on existing Group Empy Colors": '递归地根据组成员身份为组对象设置随机的对象视口颜色\nALT：根据现有的组空颜色设置组成员的颜色',
    "(X) Matcap Switch": '(X) Matcap 切换',
    "Matcap Flip": 'Matcap 翻转',
    "Use Flat Shadows": '使用平面阴影',
    "Use Shadows when in Flat Lighting": "在平面照明下使用阴影",
    "Use Scene Lights, Ambient Occlusion and Screen Space Reflections": '使用场景灯光、环境光遮蔽和屏幕空间反射',
    "Use Bloom and Screen Space Refractions": '使用泛光和屏幕空间折射',
    "Use Scene World and Volumetrics.\nCreate Principled Volume node if necessary": '使用场景世界和体积光。\n如果需要，创建主体积节点',
    "Choose Local or World space based on whether driver object is parented": '基于驱动对象是否被父物体化，选择局部或世界空间',
    "Add to Scene Collection": '添加到场景集合',
    "Add to Object Collections": '添加到物体集合',
    "Use Viewport Compositing": '使用视口合成',
    "Wireframe Color Type:": '线框颜色类型:',
    "Show object color on wireframe": '显示线框时对象颜色',
    "Draw Axes Size": '绘制坐标轴大小',
    "Draw Axes Alpha": '绘制坐标轴透明度',
    "Draw Axes in Screen Space": '在屏幕空间绘制坐标轴',
    "Draw Active's Object Axes": '绘制活动对象的坐标轴',
    "Draw Cursor's Axes": '绘制光标的坐标轴',
    "Render Engine": '渲染引擎',
    "Render Device": '渲染驱动',
    "Lighting Method": '照明方法',
    "Lighting Method for Solid/Texture Viewport Shading": '固体/纹理视口着色的照明方法',
    "Adjust Lights when Rendering": '渲染过程中调整光源',
    "Adjust Lights Area Lights when Rendering, to better match Eevee and Cycles": '渲染过程中调整面光源,以更好地匹配 Eevee 和 Cycles',
    "Divider used to calculate Cycles Light Strength from Eeeve Light Strength": '用于从 Eevee 光强计算 Cycles 光强的除数',
    "Last Light Adjustment": '最后的光照调整',
    "Have Lights been decreased by the init render handler?": '渲染初始化处理器是否已降低了光源强度?',
    "Enforce hide_render setting when Viewport Rendering": '在视口渲染时强制执行 hide_render 设置',
    "Enfore hide_render setting for objects when Viewport Rendering": '在视口渲染时对物体强制执行 hide_render 设置',
    "Batch Apply Bevel Shader to visible Materials": '批量将倒角着色器应用到可见材质上',
    "Use Bevel Shader": '使用倒角着色器',
    "Consider Object Dimensions for Bevel Radius Modulation": '考虑物体尺寸调节倒角半径',
    "Samples": '采样',
    "Bevel Shader Samples": '倒角着色器采样',
    "Radius": '半径',
    "Bevel Shader Global Radius": '倒角着色器全局半径',
    "Custom Local Views": '自定义本地视图',
    "Custom Cursor Views": '自定义游标视图',
    "Use Custom Views, based on the active object's orientation": '根据当前选中物体的朝向使用自定义视图',
    "Use Custom Views, based on the cursor's orientation": '根据游标的朝向使用自定义视图',
    "Align Mode": '对齐模式',
    "Background Strength": '背景强度',
    "View Axis": '视图轴',
    "Align Custom View to Active Object\nALT: Align View to Active %s": '将自定义视图对准活动对象\nALT：将视图对准活动%s',
    "Align Custom View to Cursor\nALT: Align View to Active %s": "将自定义视图对准光标\nALT：将视图对准活动%s",
    "Align View to World\nALT: Align View to Active to Active %s": '将视图对准世界\nALT：将视图对准活动%s',
    "Verts": '顶点',
    "Smart View Cam": '智能视图相机',
    "Default: View Active Scene Camera\nNo Camera in the Scene: Create Camera from View\nCamera Selected: Make Selected Camera active and view it.\nAlt + Click: Create Camera from current View.": '默认：查看活动场景相机\n场景中没有相机：从视图创建相机\n选择了相机：激活选定的相机并查看它。\n按住Alt键 + 单击：从当前视图创建相机。',
    "Make Active": '设为活动',
    "Make selected Camera active.": '将选中的相机设为活动相机。',
    "M4A1: Next Cam": '下一相机',
    "M4A1: Toggle Camera Perspective/Ortho": '切换相机为透视/正交投影',
    "Toggle Active Scene Camera Perspective/Ortho": '切换当前场景相机为透视/正交投影',
    "M4A1: Toggle View Perspective/Ortho": '切换视图为透视/正交投影',
    "Toggle Viewport Perspective/Ortho": '切换视口为透视/正交投影',
    "M4A1: Toggle Orbit Method": '切换轨道方式',
    "Change Orbit Method from Turntable to Trackball": '将旋转方式从旋转台切换到轨迹球',
    "Change Orbit Method from Trackball to Turntable": '将旋转方式从轨迹球切换到旋转台',
    "Turntable": '旋转台',
    "M4A1: Toggle Orbit Selection": '切换旋转选择',
    "Disable Orbit around Selection": '禁用围绕选择物体旋转',
    "Enable Orbit around Selection": '启用围绕选择物体旋转',
    "M4A1: Reset Viewport": '重置视口',
    "Perfectly align the viewport with the Y axis, looking into Y+": '将视口完美对齐到Y轴,朝向Y+方向',
    "Orthographic": '正交投影',
    "Perspective": '透视投影',
    "Reset Viewport": '重置视口',
    "Custom Views": '自定义视图',
    "(Q) Previous Cam": '(Q) 上一相机',
    "(W) Next Cam": '(W) 下一相机',
    "Cam to view": '将相机对准视图',
    "Unlock from View": '从视图中解锁',
    "Lock to View": '锁定到视图',
    "Front": '前',
    "Orbit Selection": '围绕选择对象轨道',
    "Viewport and Cameras": '视口和相机',
    "to %s": '到%s',
    "Vert": '点',
    "Face": '面',
    "Object Origin": '物体原点',
    "Clean Up HUD Fade Time (seconds)": '清理HUD渐隐时间(秒)',
    "Select Hierarchy HUD Fade Time (seconds)": '选择层级HUD渐隐时间(秒)',
    "Clipping Toggle HUD Fade Time (seconds)": '裁剪指示器HUD渐隐时间(秒)',
    "Group HUD Fade Time (seconds)": '组HUD渐隐时间(秒)',
    "Tools Pie HUD Fade Time (seconds)": '工具菜单HUD渐隐时间(秒)',
    "Flick Distance": '快速移动距离',
    "Select Center Objects, Select/Hide Wire Objects, Select Hierarchy": '选择中心对象、选择/隐藏网格对象、选择层级',
    "Easily turn Cylinder Faces into Thread": '将圆柱面容易转换为螺纹',
    "Filebrowser Tools": '文件浏览器工具',
    "Additional Tools/Shortcuts for the Filebrowser (and Assetbrowser)": '文件浏览器(和资产浏览器)的其他工具/快捷键',
    "Views Pie": '视图菜单',
    "Control views. Create and manage cameras": '控制视图。创建和管理相机。',
    "Select Children": '选择子级',
    "Select Children (incl.)": '选择子级(含自身)',
    "Select Children (unhide)": '选择子级（取消隐藏）',
    "Select Children (incl. + unhide)": '选择子级（含自身 + 取消隐藏）',
    "Select Parents": '选择父级',
    "Select Parents (incl.)": '选择父级（含自身）',
    "Select Parents (unhide)": '选择父级（取消隐藏）',
    "Select Parents (incl. + unhide)": '选择父级（含自身 + 取消隐藏）',
    "M4A1: Select Center Objects": 'M4A1:选择中心物体',
    "Selects Objects in the Center, objects, that have verts on both sides of the X, Y or Z axis.": '选择中心对象，即在 X、Y 或 Z 轴两侧都有顶点的对象。',
    "M4A1: Select Wire Objects": '选择线框对象',
    "Select Objects set to WIRE display type\nALT: Hide Objects\nCLTR: Include Empties": '选择显示类型设置为线框的对象\nALT：隐藏对象\nCTRL：包括空物体',
    "M4A1: Select Hierarchy": 'M4A1:选择层级',
    "Select Hierarchy Down": '选择层级下方',
    "Hierarchy Direction": '层级方向',
    "Include Selection": '包括选择',
    "Include Current Selection": '包括当前选择',
    "Include Mod Objects": '包括修改器对象',
    "Include Mod Objects, even if they aren't parented": '包括修改器对象,即使它们未被父子关联',
    "Unhide + Select": '取消隐藏并选择',
    "Unhide and Select hidden Children/Parents, if you encounter them": '取消隐藏并选择遇到的隐藏子级/父级',
    "Select Recursive Children": '递归选择子级',
    "Select Children Recursively": '递归选择子级',
    "Select Recursive Parents": '递归选择父级',
    "Select Parents Recursively": '递归选择父级',
    "with {} Hidden Parents": '包括隐藏的父级',
    "Reached Top of Hierarchy": '到达层级顶部',
    "Reached ABSOLUTE Top of Hierarchy": '已达到层级结构的绝对顶端',
    "Selecting Up ": '向上选择',
    "+ Unhiding ": '取消隐藏',
    "+ Recursive ": '递归',
    "+ Inclusive": '包容',
    "Reached Bottom of Hierarchy": '到达层级底部',
    "with {} Hidden Children": '包括隐藏的子级',
    "Reached ABSOLUTE Bottom of Hierarchy": '已达到层级结构的绝对底部',
    "Selecting Down ": '向下选择',
    "Nothing to remove.": '没有可删除的内容。',
    "Filebrowser": '文件浏览器',
    "Overlay Visibility (per-shading type)": '叠加显示性(每种阴影类型)',
    "Solid Shading": '纯色着色',
    "Material Shading": '材质着色',
    "Rendered Shading": '渲染着色',
    "Wire Shading": '线框着色',
    "Switch Background too": '同时切换背景',
    "Force Single Color Shading for Matcap 2": '为Matcap 2强制单色着色',
    "Disable Overlays for Matcap 2": '禁用Matcap 2的叠加层',
    "Force Trackball Navigation when using Custom Views": '在使用自定义视图时强制轨迹球导航',
    "Set Transform Preset when using Custom Views": '在使用自定义视图时设置变换预设',
    "Show Orbit around Active": '显示围绕活动物体的轨道',
    "Show Turntable/Trackball Orbit Method Selection": '显示转盘/轨迹球轨道选择方法',
    "Thread": '螺纹',
    "\nSHIFT: Extend Selection": '\nSHIFT：扩展选择',
    "\n   or": '\n   或者',
    "\nCTRL: Contract Selection": '\nCTRL：收缩选择',
    "\nCTRL: Expand Selection": '\nCTRL：扩展选择',
    "{} Select": '{} 选择',
    "Switch to {} Mode": '切换到{}模式',
    "Control shading, overlays, eevee and some object properties": '控制着色、覆盖、Eevee 和部分对象属性',
    'Select Center Objects':'选择中心对象',
    'Select Wire Objects':'选择线框对象',
    'Apply Transformations':'应用变换',
    'Align Relative':'相对对齐',
    'Material Picker':'材质选择器',
    'No Materials added yet!':'尚未添加材质！',
    'Check M4A1tools prefs.':'检查 M4A1tools 首选项。',
    '(X) Un-Group':'（X）取消分组',
    '(Q) Setup Group Gizmos':'（Q）设置群组图标',
    'Quad Sphere':'四面体球',
    'Cursor Spin':'光标旋转',
    'Punch It':'推进',
    'Quick Render':'快速渲染',
    'Final Render':'最终渲染',
    'Seed Count':'种子数量',
    'Seed Render':'种子渲染',
    'Final Seed Render':'最终种子渲染',
    'Edit':'编辑',
    'Apply Transformations while keeping the bevel width as well as the child transformations unchanged.':'将变换应用到对象，同时保持斜角宽度以及子对象的变换不变。',
    "Rotate Group '{}' around its {} Axis":"将 '{}' 组绕其 {} 轴旋转",
    'ℹℹ Illegal Selection ℹℹ':'ℹℹ  非法选择  ℹℹ',
    "You can't create a group from a selection of Objects that are all already parented to something (other other than group empties)":"你不能从已经都有父级关联的对象（除了群组空对象之外）的选择中创建群组。",
    '{} Goup: {}':'{} 组: {}',
    'Sub':'子',
    'Root':'根',
    "Added {} objects to group '{}'":"已将 {} 个对象添加到群组'{}'",
    'Removed {} objects from their group':"从它们的群组中移除了 {} 个对象",
    'M4A1: Toggle Outliner Children':'M4A1:切换大纲子项',
    'M4A1: Toggle Outliner Group Mode':'M4A1:切换大纲组模式',
    'M4A1: Collapse Outliner':'M4A1: 折叠大纲视图',
    'M4A1: Expand Outliner':'M4A1: 展开大纲视图',
    'Pose: {}{}':'姿势: {}{}',
    ' (remove)':' (移除)',
    'Preview Alpha: {}':'预览透明: {}',
    'M4A1: Transform Group':'M4A1: 变换图层组',
    'Pose: ':'姿势: ',
    'Alpha: ':'透明度: ',
    'M4A1: Setup Group Gizmos':'M4A1: 设置组小部件',
    'show_group_{}_rotation':'显示组 {} 的旋转',
    ' Global: {}':' 全局: {}',
    'M4A1: Set Group Pose':'M4A1: 设置组姿态',
    'M4A1: Update Group Pose':'M4A1: 更新组姿态',
    'Update Up':'更新朝上',
    'Update Poses Up the Hierarchy too':'同时更新层次结构上方的姿态',
    'Update Unlinked':'更新未链接的',
    'Update Poses, that have been unlinked too':'同时更新那些已经被取消链接的姿态',
    'Edit Mode':'编辑模式',
    'Horizontal':'水平',
    'Vertical':'垂直',
    'Shortest Path':'最短路径',
    'in Center':'居中',
    'Topo':'拓扑',
    'Select more than 1 vertex.':'选择了多个顶点。',
    'Select the last vertex without Box or Circle Select.':'不使用框选或圆形选择,选择最后一个顶点。',
    'Try to position the view and mouse in a way, that clearly indicates the direction you want to slide towards':'尝试调整视角和鼠标位置,以清楚地指示您想要沿哪个方向滑动。',
    'Use Focus':'使用聚焦',
    'Surface Slide':'表面滑动',
    'Align to':'对齐到',
    'Degenerate':'简化',
    'Merge to closeby Vert':'合并到临近的顶点',
    'Focus on new Object':'聚焦新物体',
    'M4A1: Smart Vert':'M4A1: 智能顶点',
    'M4A1: Smart Edge':'M4A1: 智能边',
    'M4A1: Smart Face':'M4A1: 智能面',
    'M4A1: Clean Up':'M4A1: 清理',
    'M4A1: Clipping Toggle':'M4A1: 裁切变换',
    'M4A1: Focus':'M4A1: 聚焦',
    "M4A1: Mirror":'M4A1: 镜像',
    'M4A1: Call M4A1tools Pie':'M4A1: 呼出菜单',
    "M4A1: Open in System's filebrowser":'M4A1: 在系统文件浏览器中打开',
    'M4A1: Toggle Filebrowser':'M4A1: 切换文件浏览器',
    'M4A1: Cycle Thumbnail Size':'M4A1: 循环缩略图大小',
    'M4A1: Group':'M4A1: 打组',
    'M4A1: Select Group':'M4A1: 选择组',
    'M4A1: Transform Edge Constrained':'M4A1: 受约束的边缘变换',
    'M4A1: Duplicate Nodes':'M4A1: 复制节点',
    'Modes':'模式',
    'UV Align':'uv对齐',
    'Inception':'初始',
    'LegacyPose':'初始姿态',
    'M4A1: Align':'M4A1: 对齐',
    'M4A1: Align Relative':'M4A1: 相对对齐',
    'M4A1: Apply Transformations':'M4A1: 应用变换',
    'M4A1: Create Assembly Asset':'M4A1: 创建装配资产',
    'Create Assembly Asset from the selected Objects':'从选定的对象创建装配资产',
    'M4A1: Assetbrowser Bookmark':'M4A1: 资产浏览器书签',
    'M4A1: Customize':'M4A1: 自定义',
    'Customize various Blender preferences, settings and keymaps.':'自定义各种Blender首选项、设置和快捷键。',
    'M4A1: Restore Keymaps':'M4A1: 恢复快捷键',
    'M4A1: Punch It':'M4A1: 打孔',
    'Manifold Extruding that works':'有效的多曲面挤出',
    'M4A1: Cursor Spin':'M4A1: 光标旋转',
    'M4A1: Un-Group':'M4A1: 取消分组',
    'M4A1: Groupify':'M4A1: 分组',
    'M4A1: Material Picker':'M4A1: 材质取色器',
    'Pick a Material from the 3D View\nALT: Assign it to the Selection too':'从3D视图中选取材质\nALT: 同时将其分配给选择',
    'M4A1: Mesh Cut':'M4A1: 网格切割',
    'M4A1: Quadsphere':'M4A1: 四边形球体',
    'Creates a Quadsphere':'创建一个四边形球体',
    'M4A1: Toggle 3D View Region':'M4A1: 切换3D视图区域',
    'M4A1: Toggle Asset Browser Region':'M4A1: 切换资产浏览器区域',
    'Toggle Asset Browser Region based on Mouse Position':'根据鼠标位置切换资产浏览器区域',
    'M4A1: Toggle Toolbar or Sidebar (Any Region)':'M4A1: 切换工具栏或侧边栏(任何区域)',
    'Toggle Toolbar or Sidebar (Any Region)':'切换工具栏或侧边栏(任何区域)',
    'M4A1: Area Dumper':'M4A1: 区域dump器',
    'M4A1: Render':'M4A1: 渲染',
    'Duplicate Nodes normaly, except for Cryptomatte V2 nodes, in that case keep the inputs and clear out the matte ids':'正常复制节点,但对于Cryptomatte V2节点,保留输入并清除遮罩ID。',
    'M4A1: Smart Drive':'M4A1: 智能驱动',
    'M4A1: Switch Driver Values':'M4A1: 切换驱动器值',
    'M4A1: set_driver_value':'M4A1: 设置驱动器值',
    'M4A1: Toggle Smooth':'M4A1: 切换平滑',
    'Toggle Smothing for Korean Bevel and SubD Objects':'切换韩式斜角和细分网格物体的平滑设置。',
    'M4A1: Surface Slide':'M4A1: 表面滑动',
    'Start Surface Sliding: modifify the topology while keeping the inital form intact':'开始表面滑动:在保持初始形状完整的情况下修改拓扑结构。',
    'M4A1: Finish Surface Slide':'M4A1: 完成表面滑动',
    'Stop Surface Sliding':'停止表面滑动',
    'M4A1: Add Thread':'M4A1: 添加螺纹',
    'M4A1: Prepare Unity Export':'M4A1: 准备Unity导出',
    'M4A1: Restore Unity Export':'M4A1: 恢复Unity导出',
    'Restore Pre-Export Object Transformations, Meshes and Modifiers':'恢复导出前的物体变换、网格和修改器设置。',
    'M4A1: Draw Group Rest Pose':'M4A1: 绘制组静止姿态',
    'Reverse the Motion':'反转动作',
    'Time (s)':'时间(秒)',
    'M4A1: Align (Edit Mesh)':'M4A1: 对齐(编辑网格)',
    'M4A1: Align Object to Edge':'M4A1: 将物体对齐到边缘',
    'M4A1: Center (Edit Mesh)':'M4A1: 居中(编辑网格)',
    'Align one or more objects to edge in active object\nALT: Snap objects to edge by proximity\nCTRL: Snap objects to edge by midpoint':'将一个或多个物体对齐到活动物体的边缘\nALT: 根据相邻性将物体卡到边缘\nCTRL: 根据中点将物体卡到边缘',
    'M4A1: Align Object to Vert':'M4A1: 将物体对齐到顶点',
    'Align one or more objects to vertice in active object':'将一个或多个物体对齐到活动物体的顶点',
    'M4A1: Straighten':'M4A1: 拉直',
    'M4A1: Create Collection':'M4A1: 创建集合',
    'M4A1: Remove from Collection':'M4A1: 从集合中移除',
    'M4A1: Purge Collections':'M4A1: 清除集合',
    'M4A1: (De)Select Collection':'M4A1: (取消)选择集合',
    'M4A1: Cursor to Origin':'M4A1: 光标移动到原点',
    'M4A1: Cursor to Selected':'M4A1: 光标移动到所选位置',
    'M4A1: Selected To Cursor':'M4A1: 所选物体移动到光标位置',
    'M4A1: Draw Label':'M4A1: 绘制标签',
    'Text to draw the HUD':'绘制HUD的文本',
    'Text Size':'文本大小',
    'Screen Coordinates':'屏幕坐标',
    'Move Up or Down':'上下移动',
    'M4A1: ShrinkWrap Grease Pencil':'M4A1: 收缩铺路铅笔',
    'Shrinkwrap current Grease Pencil Layer to closest mesh surface based on Surface Offset value':'根据表面偏移值,将当前铅笔图层收缩到最近的网格表面',
    'M4A1: Get M4A1tools Support':'M4A1: 获取M4A1工具支持',
    'Generate Log Files and Instructions for a Support Request.':'生成日志文件并提供支持请求的说明。',
    'M4A1: Image Mode':'M4A1: 图像模式',
    'M4A1: UV Mode':'M4A1: UV模式',
    'M4A1: Open Library Blend':'M4A1: 打开库Blend文件',
    'Open new Blender instance, loading the library sourced in the selected object or collection instance.':'打开一个新的Blender实例,加载在所选物体或集合实例中引用的库文件。',
    'M4A1: Origin to Active':'M4A1: 原点移动到活动物体',
    'M4A1: Origin to Cursor':'M4A1: 原点移动到光标位置',
    'M4A1: Origin to Bottom Bounds':'M4A1: 原点移动到物体底部边界',
    'Evaluated Object Bounds':'计算物体边界',
    'M4A1: Save As':'M4A1: 另存为',
    'Save as Copy':'另存为副本',
    'Save as Asset':'另存为资产',
    'Purge Orphans\nALT: Purge Orphans Recursively':'清理孤立元素\nALT: 递归清理孤立元素',
    'Shading Type':'着色类型',
    'Adjust Global Bevel Radius':'调整全局斜角半径',
    'Decrease Radius':'减小半径',
    'M4A1: Set Snapping Preset':'M4A1: 设置吸附预设',
    'Set Snapping Preset':'设置吸附预设',
    'Snap Element':'吸附元素',
    'Snap Target':'吸附目标',
    'Align Rotation':'对齐旋转',
    'M4A1: Set Tool by Name':'M4A1: 按名称设置工具',
    'Tool name/ID':'工具名称/ID',
    'M4A1: Set BoxCutter Preset':'M4A1: 设置BoxCutter预设',
    'Quickly enable/switch BC tool in/to various modes':'快速启用/切换BoxCutter工具到各种模式',
    'M4A1: Set Transform Preset':'M4A1: 设置变换预设',
    'Set Transform Pivot and Orientation at the same time.':'同时设置变换枢轴和方向。',
    'Transform Pivot':'变换枢轴',
    'Transform Orientation':'变换方向',
    'M4A1: Remove Update':'M4A1: 移除更新',
    "I changed my mind, I don't want to install this Update":"我改变主意了,我不想安装这个更新。",
    'M4A1: Use Update':'M4A1: 使用更新',
    'M4A1: Re-Scan Updates':'M4A1: 重新扫描更新',
    'Re-Scan Updates':'重新扫描更新',
    'M4A1: Align (UV)':'M4A1: 对齐(UV)',
    'M4A1: Get Icon Name Help':'M4A1: 获取图标名称帮助',
    'Top.':'上',
    'Bottom.':'下',
    'Assign':'分配',
    'Assign Material from Asset Browsr to Object under Mouse':'从资产浏览器中将材质分配给鼠标下的物体',
    'Pick Material and Assign it to Selected Objects':'选择材质并将其分配给选定的对象',
    'Pick Material and Finish':'选择材质并完成',
    'Assign Material: {}':'分配材质: {}',
    'Assign Material from Asset Browser: {}':'从资产浏览器分配材质: {}',
    'Assign from Asset Browser ':'从资产浏览器分配',
    'Pick':'拾取',
    '.blend file does not exist: {}':'.blend文件不存在: {}',
    'No material selected in asset browser!':'在资产浏览器中未选择任何材质!',
    'LOCAL or unsupported library chosen!':'选择了本地或不支持的库!',
    'Material ':'材质 ',
    'There is no asset browser in this workspace':'这个工作空间中没有资产浏览器',
    'Quick Favorites':'快速收藏夹',
    'Tool Bar':'工具栏',
    "Pick Materials from the Material Workspace's 3D View":'从材质工作空间的3D视图中选取材质',
    'Collection':'集合',
    'Based on the M3 tool, add more features to make Blender more user-friendly':'基于M3工具,添加更多功能来使Blender变得更加好用',
    'Object Mode Header Spacing':'物体模式标题间距',
    'Edit Mode Header Spacing':'编辑模式标题间距',
    'Show Material Picker':'显示材质选择器',
    'Show Material Picker in Views set to Material Shading':'在设置为材质着色的视图中显示材质选择器',
    'Show Material Picker in Views set to Rendered Shading':'在设置为渲染着色的视图中显示材质选择器',
    'Workspaces the Material Picker should appear on':'材质选择器应该出现在的工作空间',
    'Include Children':'包含子项',
    'Individual':'各自的原点',
    'Absolute Grid':'绝对网格',
    'Surface':'表面',
    'Snap to Vertices':'吸附到顶点',
    'Snap to Edges':'吸附到边',
    'Snap to Faces and Align the Rotation':'吸附到面并对齐旋转',
    'Snap to Absolute Grid Points':'吸附到绝对网格点',
    'Snap to Volumes':'吸附到体积',
    'Show Absolute Grid Snapping':'显示绝对网格吸附',
    'Show Volume Snapping':'显示体积吸附',
    'Transform Pie':'变换菜单',
    'Snapping Pie':'吸附菜单',
    'Movement of an object up, down, left and right based on perspective control and selection':'基于视角控制选择物体上下左右移动',
    'Control Move':'上下左右',
    'Control Move Offset':'移动精度',
    'Upward movement':'向上移动',
    'Downward movement':'向下移动',
    'Left movement':'向左移动',
    'Right movement':'向右移动',
    'Move towards the view':'靠近视角',
    'Move away from the view':'远离视角',
    'Move Control':'移动控制',
    # 'Selec':'aaa',
}
